from typing import Tuple


LAYOUT_DUAL_STREAM_BLOCK_INDICES: Tuple[int, ...] = (0, 3, 6, 9, 12, 15, 18)
LAYOUT_SINGLE_STREAM_BLOCK_INDICES: Tuple[int, ...] = (0, 9, 18, 27, 37)

MASK_PREDICTOR_IN_CHANNELS: int = 1
MASK_PREDICTOR_HIDDEN_CHANNEL_1: int = 32
MASK_PREDICTOR_HIDDEN_CHANNEL_2: int = 16
MASK_PREDICTOR_OUT_CHANNELS: int = 2
MASK_PREDICTOR_KERNEL_SIZE: int = 3
MASK_PREDICTOR_PADDING: int = 1

LAYOUT_SIGMA_SCALE: float = 5.0
LAYOUT_GUIDANCE_SCALE: float = 10.0
